from select_random_country import SELECT_RANDOM_COUNTRY
from select_random_genre import SELECT_RANDOM_GENRE
from select_random_year import SELECT_RANDOM_YEAR
from select_random_artist import SELECT_RANDOM_ARTIST