from auth import LOGIN_AUTH, SIGN_USER

from user import REMOVE_USER_OLD_HISTORY, INSERT_NEW_SEARCH_RESULTS, \
    FULLTEXT_SEARCH_IN_HISTORY, GET_USER_RECENT_HISTORY, GET_USER_RECENT_RESULTS, \
    GET_USER_RESULTS_COUNT

from utils import SELECT_RANDOM_YEAR, SELECT_RANDOM_GENRE, SELECT_RANDOM_COUNTRY, \
    SELECT_RANDOM_ARTIST

from search import MOST_HATED_PAIR_FROM_GENRE, \
    MOST_COMMON_GENRE_IN_COUNTRY, MOST_RELEVANT_ARTISTS_GENRE_SONGS, \
    VIDEOS_CUSTOM_STATISTICS, MOST_HATED_ARTISTS_OF_YEAR_RANGE, \
    ARTIST_WITH_LONGEST_SONGS_AVG_IN_GENRE, MOST_AMBIVALENT_SONGS_OF_ARTIST, \
    MOST_HATED_GENRE_SONGS, MOST_HATED_SONGS_OF_YEAR, MOST_POPULAR_SONGS
